name = "muelle01"
uuid = "0dd4645d-dbd7-4523-b048-f6e51b1b10a5"
authors = ["janr <janr.devel@gmail.com>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
CairoMakie = "0.15.6"
DifferentialEquations = "7.16.1"
GLMakie = "0.13.6"
PlutoUI = "0.7.71"
WGLMakie = "0.13.6"
